### ISSUE TITLE
Overlap Issue

### ISSUE THREAD

**Issue by AnushaSridharan** [Horopter/Chess-2020#1]
[overlap-issue.log](https://github.com/Horopter/Chess-2020/files/5027978/overlap-issue.log)

![image](https://user-images.githubusercontent.com/5353215/89407587-aeddc300-d73c-11ea-995e-8c9d2ec4dfbb.png)

**Comment by Horopter** [comment]
Please take the latest revision and see if this issue persists.

**Comment by AnushaSridharan** [comment]
positions are logged undefined
[pos-undefined.log](https://github.com/Horopter/Chess-2020/files/5029153/pos-undefined.log)

**Comment by Horopter** [comment]
Can you elaborate on sequence of steps leading to that point? Like, what was expected instead of undefined so that I can look into it?

**Comment by Horopter** [comment]
Fixed the rendering issue.
