### ISSUE TITLE
Log for pick action

### ISSUE THREAD

**Issue by AnushaSridharan** [Horopter/Chess-2020#2]
[log-for-pick-action.log](https://github.com/Horopter/Chess-2020/files/5034854/log-for-pick-action.log)

![image](https://user-images.githubusercontent.com/5353215/89534838-2f6ef300-d813-11ea-881a-07ccbb958ce4.png)

App.js:69 Move
App.js:26 Pick :  Pawn WHITE G7 A7
App.js:69 Move
App.js:26 Pick :  Pawn WHITE H7 G7
App.js:69 Move
App.js:26 Pick :  Pawn WHITE F7 H7

**Comment by Horopter** [comment]
Fixed with [this](https://github.com/Horopter/Chess-2020/commit/ec6c7dd63817547145004d19eccefa9718e0464e) change
